### ISSUE TITLE
Username publicly exposed

### ISSUE THREAD

**Issue by rthompson-tec** [tecgovtnz/scripts#1]
Username Zadock Allen is publicly exposed ansible-utils/ubuntu-install-ansible.sh

**Comment by gbrowne-tec** [comment]
@rthompson-tec Is this on the syslog servers? Could you provide a little more detail and next steps? Thanks

**Comment by rthompson-tec** [comment]
@gbrowne-tec 

This repo (scripts) is public, the bash script stored in this repo that is used for ansible setup exposes the username ZadockAllen.
see file 'scripts/ansible-utils/ubuntu-install-ansible.sh' line 22

Ideally no part of the credentials are exposed publicly, but if they must be I would recommend using a username that is not used elsewhere in the platform.

**Comment by cpagesinclair-tec** [comment]
Hi @gsmartpax8 - Can you please review and advise options here. Ideally we don't want to expose any usernames publicly, or otherwise if this is not possible to use a different username than used everywhere else

**Comment by gsmartpax8** [comment]
Potentially can use GitHub Action variables on this. @gbrowne-tec, Can you approve 2 hours for us to investigate, amend and test?

**Comment by gbrowne-tec** [comment]
Approved

Thanks,


Gavin Browne

Architect / Technical Lead
Information Directorate

M:021 276-9639

***@***.***

PO Box 27-048, Wellington, New Zealand

www.tec.govt.nz<http://www.tec.govt.nz/>

________________________________

**Comment by gsmartpax8** [comment]
@daovietduy99  has begun working on this

**Comment by daovietduy99** [comment]
Done, please help to check

**Comment by gsmartpax8** [comment]
Duy has made amendments to the GitHub pipeline, this is now hidden. Please test

**Comment by rthompson-tec** [comment]
Will deploy a runner to test along with #164 but looks good.

**Comment by rthompson-tec** [comment]
Username no longer exposed and vmmgtghraue01-dev has been redeployed successfully.
